Registration is done!
DanilFilikov/AdvancedServer pull request #1
Opened 2023-06-14 08:57 UTC by DanilFilikov

2023-06-14 09:37 UTC, MVlasovD requested changes

2023-06-14 09:37 UTC, MVlasovD commented on build.gradle
>  }
название проекта не по требованиям

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/config/SecuriytConfig.java
> +    private static final String LOGIN_ENDPOINT = "/auth/**";
эндпойнты лучше вынести в отдельный интерфейс с константами

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/repository/UserRepo.java
> +    Optional<UserEntity> findByName(String name);
по какому имени ты собираешься искать?

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/security/JwtUserDetailsService.java
> +        }
как мы обрабатываем опшионал?

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/security/jwt/JwtTokenProvider.java
> +        return bCryptPasswordEncoder;
```suggestion
        return new BCryptPasswordEncoder()
```

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/security/jwt/JwtTokenProvider.java
> +    @Bean
этот бин у тебя работает?

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/security/jwt/JwtUser.java
> +        return null;
null ?
и ниже

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/model/CustomSuccessResponse.java
> +package com.example.demo.model;
имя пакета model?

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/impl/UserServiceImpl.java
> +        return CustomSuccessResponse.getSuccessResponse(LoginUserDto.mapToDto(userEntity, token));
маппаем mapstruct'ом

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/dto/LoginUserDto.java
> +    }
mapstruct

2023-06-14 09:37 UTC, MVlasovD commented on src/main/java/com/example/demo/dto/LoginUserDto.java
> +    @Email(message = ValidationConstants.USER_EMAIL_NOT_VALID)
по докам нет валидации этого дто

2023-06-14 09:43 UTC, DanilFilikov commented on src/main/java/com/example/demo/security/jwt/JwtTokenProvider.java
> +    @Bean
Da

2023-06-14 14:22 UTC, MVlasovD requested changes

2023-06-14 14:22 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/error/ErrorCodes.java
> +
```suggestion
```

2023-06-14 14:22 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/repository/UserRepo.java
> +    Optional<UserEntity> findByName(String name);
где используешь этот метод?

по требованиям все методы репо должны иметь запросы к БД

2023-06-14 14:22 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/security/JwtUserDetailsService.java
> +        }
обработка опшионала

2023-06-14 14:22 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/security/JwtUserDetailsService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String uuid) throws UsernameNotFoundException {
```

2023-06-14 14:22 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/security/jwt/JwtAuthentificationException.java
> +public class JwtAuthentificationException extends AuthenticationException {
зачем тебе этот класс?

2023-06-14 14:22 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/security/jwt/JwtTokenProvider.java
> +        return bCryptPasswordEncoder;
```suggestion
        return new BCryptPasswordEncoder();
```

2023-06-14 14:22 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/security/jwt/JwtUserFactory.java
> +
```suggestion
```

2023-06-14 14:39 UTC, MVlasovD requested changes

2023-06-14 14:39 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/security/jwt/JwtTokenProvider.java
> +        return null;
Nit: 

не очень данный возврат

2023-06-14 14:39 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/security/jwt/JwtTokenProvider.java
> +                .signWith(SignatureAlgorithm.HS256, secret)
```suggestion
                .signWith(SignatureAlgorithm.HS512, secret)
```

2023-06-14 14:39 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/repository/UserRepo.java
> +    Optional<UserEntity> findByEmail(String email);
запросы

2023-06-15 08:09 UTC, MVlasovD requested changes

2023-06-15 08:09 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/repository/UserRepo.java
> +    @Transactional()
она здесь не нужна

2023-06-15 08:09 UTC, MVlasovD commented on src/main/java/com/example/filikov_advanced_server/repository/UserRepo.java
> +    @Transactional
не нужна
почитай про эту аннотацию
https://www.baeldung.com/spring-transactional-propagation-isolation

2023-06-15 08:18 UTC, MVlasovD approved these changes

2023-06-15 08:43 UTC, merged